// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbNzp2hcPDxYYShqt_V_rOBXHAQb0W2iU',
    appId: '1:539755786245:web:c78db896ed58c03e762c6c',
    messagingSenderId: '539755786245',
    projectId: 'tt022025-2a071',
    authDomain: 'tt022025-2a071.firebaseapp.com',
    storageBucket: 'tt022025-2a071.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApGb3_Duxjx6l0DAxHQmbPgVncDgCaqB0',
    appId: '1:539755786245:android:10e8af9f3d57d548762c6c',
    messagingSenderId: '539755786245',
    projectId: 'tt022025-2a071',
    storageBucket: 'tt022025-2a071.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5DfNx6vxoTGMq4maJrWVP2sABya-uotA',
    appId: '1:539755786245:ios:42434de3f380f060762c6c',
    messagingSenderId: '539755786245',
    projectId: 'tt022025-2a071',
    storageBucket: 'tt022025-2a071.firebasestorage.app',
    iosBundleId: 'com.example.kiemTraNangLucSoTt022025d',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5DfNx6vxoTGMq4maJrWVP2sABya-uotA',
    appId: '1:539755786245:ios:42434de3f380f060762c6c',
    messagingSenderId: '539755786245',
    projectId: 'tt022025-2a071',
    storageBucket: 'tt022025-2a071.firebasestorage.app',
    iosBundleId: 'com.example.kiemTraNangLucSoTt022025d',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbNzp2hcPDxYYShqt_V_rOBXHAQb0W2iU',
    appId: '1:539755786245:web:fc32cdce7d041b2d762c6c',
    messagingSenderId: '539755786245',
    projectId: 'tt022025-2a071',
    authDomain: 'tt022025-2a071.firebaseapp.com',
    storageBucket: 'tt022025-2a071.firebasestorage.app',
  );
}
